### ISSUE TITLE
does this support Bluetooth printer 

### ISSUE THREAD

**Issue by ccfiel** [feedmepos/flutter_printer#1]
Does this package support bluetooth printer?

**Comment by victorshx** [comment]
Hi Chris,

Bluetooth printer is not in our use case, maybe in the future. 

However, you can take a look at [esc_pos_bluetooth](https://github.com/andrey-ushakov/esc_pos_bluetooth/blob/master/lib/src/printer_bluetooth_manager.dart) implementation. Hope it helps you!

**Comment by ccfiel** [comment]
Hello @victorshx 

Actually we are using that package currently but the problem its not maintain and the Bluetooth connection is not stable so trying to find a package that is maintain and stable.

**Comment by ccfiel** [comment]
maybe we can use this package https://pub.dev/packages/flutter_blue to support bluetooth ? what do you think?

**Comment by victorshx** [comment]
Sadly I do not have a Bluetooth printer, and our clients prefer USB/IP printers. We’re migrating our codebase to Flutter so I’ll look into it when we are done with the rewrite. And we welcome PR 😄

**Comment by ccfiel** [comment]
ok wiil try to create a bluetooth PR for this :) is this package already in production use?

**Comment by ccfiel** [comment]
I tried to read you code this package usecase is you have printHtml this will convert to image and print the image to the printer? correct?

**Comment by victorshx** [comment]
> ok wiil try to create a bluetooth PR for this :) is this package already in production use?

Thanks! All the libraries in this repo will be used in production; we'll maintain it and improve the code structure since it's a critical use case for us.


> I tried to read you code this package usecase is you have printHtml this will convert to image and print the image to the printer? correct?

Yes, our use case is to print an HTML receipt template to the printer for F&B restaurants. Don't mind the spaghetti code, I'm new to Flutter, and this is my first time playing with printer 😅

**Comment by ccfiel** [comment]
@victorshx why did you decide to printer it to image? In our experience its slow because in conversion to image and you cannot print big image. We got errors. Do you have the same experience?

**Comment by victorshx** [comment]
> @victorshx why did you decide to printer it to image? In our experience its because in conversion to image and you cannot print big image. We got errors. Do you have the same experience?

Because we need to support multiple printers and all 3 OSes, having image bytes and converting to printer bitmap/raster commands is much consistent. I did not face the issue, it can print very long images. 

I agree that is slow, but it can be further optimised. On Windows, converting HTML to image and sending TSPL image raster commands using PrintSpooler takes about 700ms.

You can take a look at [escpos](https://github.com/feedmepos/flutter_printer/blob/master/flutter_pos_printer/lib/src/printers/escpos.dart#L13) and [tspl](https://github.com/feedmepos/flutter_printer/blob/master/flutter_pos_printer/lib/src/printers/tspl.dart#L217) for the implementation.
